### ISSUE TITLE
zkSync 500 error while trying to get faucet drop

### ISSUE THREAD

**Issue by mderazon** [matter-labs/testnet-faucet#2]
This seems to be the right place to open this issue
See https://github.com/matter-labs/zksync/issues/350

Maybe some issue with https://github.com/matter-labs/testnet-faucet/blob/30d316c4299166aa00a09f31e8a693b07a034a0d/app/app.ts#L78

(guess it is fragile after all ?)

**Comment by adrianchifor** [comment]
Hey @mderazon, we believe this is now resolved, are you still seeing it?

**Comment by RomanBrodetski** [comment]
close as inactive
